# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45052042faff0bee1cd19a95ec5332eb9adc5aac487ed805a4ead822e4b67412358b7a2ae1a41294fe8de7dab22ecab6f06287380b6ba01926c0a44289a992f8

test:
  secret_key_base: 578b89584a9b6458aa38ee02358f47bacc2675497fe675a609b71930ab75f3abb40502bb0506826911f5987e4b3b888f8fa3614bf3bcda5859f54be317b2650f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
